### ISSUE TITLE
MapResolverStrategy does not work correctly.

### ISSUE THREAD

**Issue by munnitz** [franalma/MapsWrapper#11]
On both Huawei devices with only HMS installed or GMS deactivated and HMS activated, the maps wrapper still uses a Google MapView instead of a Huawei one which makes getMapAsync return null (since the GMS are not available). This can only be fixed by enforcing Huawei.
```
2020-10-27 13:42:40.993 430-430/xx.xx.xx E/XXX: BaseMapFragment
    java.lang.NullPointerException: Attempt to invoke virtual method 'maps.wrapper.GroundOverlay maps.wrapper.ExtendedMap.addGroundOverlay(maps.wrapper.GroundOverlayOptions)' on a null object reference
        at xxx.BaseMapFragment.showLayer(BaseMapFragment.java:784)
        at xxx.fragments.BaseMapFragment.onLayerLoaded(BaseMapFragment.java:721)
        at xxx.fragments.ForecastMapFragment.onLayerLoaded(ForecastMapFragment.java:543)
        at xxx.controllers.ForecastLayerController.onBitmapLoadResult(ForecastLayerController.kt:65)
        at xxx.glide.LayerBitmapSimpleTarget.onResourceReady(LayerBitmapSimpleTarget.kt:20)
        at xxx.glide.LayerBitmapSimpleTarget.onResourceReady(LayerBitmapSimpleTarget.kt:13)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:582)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:544)
        at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:152)
        at com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:398)
        at android.os.Handler.handleCallback(Handler.java:809)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7377)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
```

**Comment by munnitz** [comment]
it seems to be that GoogleApiAvailability still returns ConnectionResult.SUCCESS for some reason even though GMS are not available. 
This issue occurs when not specifying a selection strategy
